name: Test Model on main PR
run-name: Testing Model 🤘
on:
  pull_request:
    branches:
      - artificial-main
    paths:
      - '**.py'
  workflow_dispatch:
    
jobs:
  train_and_test:
    name: Train and Test Model
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.23.3
          cache: false

      - name: Train Model
        uses: dagger/dagger-for-github@v6
        with:
          verb: run
          args: go run pipeline.go
          version: "0.14.0"

      - name: Upload Model Artifact
        uses: actions/upload-artifact@v4.4.0
        with:
          name: model
          path: model.pkl

      - name: Run Model Inference Test Action
        uses: lasselundstenjensen/itu-sdse-project-model-validator@main
          