name: Test Model Artifact

on:
  pull_request:
    branches:
      - test-main
  workflow_run:
    workflows:
      - Test Model on main PR
    types:
      - completed
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Download artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: test_action.yml
          workflow_conclusion: success
