name: Test Model Artifact

on:
  workflow_run:
    workflows:
      - Test Model on main PR
    types:
      - completed

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Download Artifact from "Test Model on main PR"
        uses: actions/download-artifact@v3
        with:
          name: model 
          path: ./artifacts

      - name: Verify Artifact Exists
        run: |
          if [ ! -f "./artifacts/model.pkl" ]; then
            echo "Model artifact not found!"
            exit 1
          else
            echo "Model artifact verified."
          fi
