# Workaround for required checks when file patterns don't match.

name: No Op
on:
  pull_request:

jobs:
  train_and_upload:
    runs-on: ubuntu-latest
    steps:
      - name: Do nothing
        run: exit 0